AWSTemplateFormatVersion: '2010-09-09'
Description: OpenSearch CloudWatch Alarms
Parameters:
  SNSTopicArn:
    Type: String
    Description: SNS Topic ARN for alarm notifications
    AllowedPattern: arn:aws:sns:[a-z0-9-]+:[0-9]{12}:.+
    ConstraintDescription: Must be a valid SNS Topic ARN
Resources:
  OpenSearchWarningAlarm0:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-OpenSearch-mytestos-Shards.unassigned-Warning
      AlarmDescription: 未分配分片数 - 表示集群健康问题
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max("Shards.unassigned") FROM "AWS/ES" WHERE DomainName
          = 'mytestos'
        Period: 300
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  OpenSearchCriticalAlarm1:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-OpenSearch-mytestos-Shards.unassigned-Critical
      AlarmDescription: 未分配分片数 - 表示集群健康问题
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max("Shards.unassigned") FROM "AWS/ES" WHERE DomainName
          = 'mytestos'
        Period: 300
      Threshold: 5
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  OpenSearchWarningAlarm2:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-OpenSearch-mytestos-Shards.activePrimary-Warning
      AlarmDescription: 集群主分片数量 - 默认单节点分片1000
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max("Shards.activePrimary") FROM "AWS/ES" WHERE DomainName
          = 'mytestos'
        Period: 300
      Threshold: 900
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  OpenSearchCriticalAlarm3:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-OpenSearch-mytestos-Shards.activePrimary-Critical
      AlarmDescription: 集群主分片数量 - 默认单节点分片1000
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max("Shards.activePrimary") FROM "AWS/ES" WHERE DomainName
          = 'mytestos'
        Period: 300
      Threshold: 950
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  OpenSearchCriticalAlarm4:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-OpenSearch-mytestos-ClusterStatus.green-Critical
      AlarmDescription: 集群状态 - 绿色表示健康
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max("ClusterStatus.green") FROM "AWS/ES" WHERE DomainName
          = 'mytestos'
        Period: 300
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  OpenSearchWarningAlarm5:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-OpenSearch-mytestos-ClusterStatus.yellow-Warning
      AlarmDescription: 集群状态 - 黄色表示部分不可用
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max("ClusterStatus.yellow") FROM "AWS/ES" WHERE DomainName
          = 'mytestos'
        Period: 300
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  OpenSearchCriticalAlarm6:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-OpenSearch-mytestos-ClusterStatus.red-Critical
      AlarmDescription: 集群状态 - 红色表示不可用
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max("ClusterStatus.red") FROM "AWS/ES" WHERE DomainName
          = 'mytestos'
        Period: 300
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  OpenSearchInfoAlarm7:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-OpenSearch-mytestos-CPUUtilization-Info
      AlarmDescription: CPU使用率
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(CPUUtilization) FROM "AWS/ES" WHERE DomainName = 'mytestos'
        Period: 300
      Threshold: 70
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  OpenSearchWarningAlarm8:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-OpenSearch-mytestos-CPUUtilization-Warning
      AlarmDescription: CPU使用率
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(CPUUtilization) FROM "AWS/ES" WHERE DomainName = 'mytestos'
        Period: 300
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  OpenSearchCriticalAlarm9:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-OpenSearch-mytestos-CPUUtilization-Critical
      AlarmDescription: CPU使用率
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(CPUUtilization) FROM "AWS/ES" WHERE DomainName = 'mytestos'
        Period: 300
      Threshold: 90
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  OpenSearchInfoAlarm10:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-OpenSearch-mytestos-JVMMemoryPressure-Info
      AlarmDescription: JVM内存压力
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(JVMMemoryPressure) FROM "AWS/ES" WHERE DomainName =
          'mytestos'
        Period: 300
      Threshold: 70
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  OpenSearchWarningAlarm11:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-OpenSearch-mytestos-JVMMemoryPressure-Warning
      AlarmDescription: JVM内存压力
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(JVMMemoryPressure) FROM "AWS/ES" WHERE DomainName =
          'mytestos'
        Period: 300
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  OpenSearchCriticalAlarm12:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-OpenSearch-mytestos-JVMMemoryPressure-Critical
      AlarmDescription: JVM内存压力
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(JVMMemoryPressure) FROM "AWS/ES" WHERE DomainName =
          'mytestos'
        Period: 300
      Threshold: 90
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  OpenSearchWarningAlarm13:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-OpenSearch-mytestos-MasterCPUUtilization-Warning
      AlarmDescription: 主节点CPU使用率
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(MasterCPUUtilization) FROM "AWS/ES" WHERE DomainName
          = 'mytestos'
        Period: 300
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  OpenSearchCriticalAlarm14:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-OpenSearch-mytestos-MasterCPUUtilization-Critical
      AlarmDescription: 主节点CPU使用率
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(MasterCPUUtilization) FROM "AWS/ES" WHERE DomainName
          = 'mytestos'
        Period: 300
      Threshold: 90
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  OpenSearchCriticalAlarm15:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-OpenSearch-mytestos-MasterJVMMemoryPressure-Critical
      AlarmDescription: 主节点JVM内存压力
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(MasterJVMMemoryPressure) FROM "AWS/ES" WHERE DomainName
          = 'mytestos'
        Period: 300
      Threshold: 90
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  OpenSearchWarningAlarm16:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-OpenSearch-mytestos-FreeStorageSpace-Warning
      AlarmDescription: 可用存储空间 - 低于20GB告警 (20GB in MB)
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(FreeStorageSpace) FROM "AWS/ES" WHERE DomainName =
          'mytestos'
        Period: 300
      Threshold: 20480
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  OpenSearchCriticalAlarm17:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-OpenSearch-mytestos-FreeStorageSpace-Critical
      AlarmDescription: 可用存储空间 - 低于10GB告警 (10GB in MB)
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(FreeStorageSpace) FROM "AWS/ES" WHERE DomainName =
          'mytestos'
        Period: 300
      Threshold: 10240
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
