AWSTemplateFormatVersion: '2010-09-09'
Description: EKS EC2 Node CloudWatch Alarms - Tag-based using eks:cluster-name (11 alarms)
Parameters:
  EKSClusterName:
    Type: String
    Description: EKS cluster name (used to filter EC2 nodes via eks:cluster-name tag)
    AllowedPattern: .+
    ConstraintDescription: EKSClusterName is required and cannot be empty
  BusinessTagValue:
    Type: String
    Description: Business tag value for alarm naming (e.g., Production, Staging)
    AllowedPattern: .+
    ConstraintDescription: BusinessTagValue is required and cannot be empty
  SNSTopicArn:
    Type: String
    Description: SNS Topic ARN for alarm notifications
    AllowedPattern: arn:aws:sns:[a-z0-9-]+:[0-9]{12}:.+
    ConstraintDescription: Must be a valid SNS Topic ARN
Resources:
  EKSEC2CPUInfoAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName:
        Fn::Sub: ${BusinessTagValue}-EKS-${EKSClusterName}-EC2-CPUUtilization-Info
      AlarmDescription: EKS节点CPU使用率 - Info级别告警
      Metrics:
      - Id: m1
        ReturnData: true
        Expression:
          Fn::Sub: SELECT MAX(CPUUtilization) FROM "AWS/EC2" WHERE "eks:cluster-name" = '${EKSClusterName}' GROUP BY InstanceId ORDER BY MAX() DESC
        Period: 300
      Threshold: 85
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  EKSEC2CPUWarningAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName:
        Fn::Sub: ${BusinessTagValue}-EKS-${EKSClusterName}-EC2-CPUUtilization-Warning
      AlarmDescription: EKS节点CPU使用率 - Warning级别告警
      Metrics:
      - Id: m1
        ReturnData: true
        Expression:
          Fn::Sub: SELECT MAX(CPUUtilization) FROM "AWS/EC2" WHERE "eks:cluster-name" = '${EKSClusterName}' GROUP BY InstanceId ORDER BY MAX() DESC
        Period: 300
      Threshold: 90
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  EKSEC2CPUCriticalAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName:
        Fn::Sub: ${BusinessTagValue}-EKS-${EKSClusterName}-EC2-CPUUtilization-Critical
      AlarmDescription: EKS节点CPU使用率 - Critical级别告警
      Metrics:
      - Id: m1
        ReturnData: true
        Expression:
          Fn::Sub: SELECT MAX(CPUUtilization) FROM "AWS/EC2" WHERE "eks:cluster-name" = '${EKSClusterName}' GROUP BY InstanceId ORDER BY MAX() DESC
        Period: 300
      Threshold: 95
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  EKSEC2NetworkInInfoAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName:
        Fn::Sub: ${BusinessTagValue}-EKS-${EKSClusterName}-EC2-NetworkIn-Info
      AlarmDescription: EKS节点网络入口带宽 - Info级别告警
      Metrics:
      - Id: m1
        ReturnData: true
        Expression:
          Fn::Sub: SELECT MAX(NetworkIn) FROM "AWS/EC2" WHERE "eks:cluster-name" = '${EKSClusterName}' GROUP BY InstanceId ORDER BY MAX() DESC
        Period: 300
      Threshold: 157286400
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  EKSEC2NetworkInWarningAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName:
        Fn::Sub: ${BusinessTagValue}-EKS-${EKSClusterName}-EC2-NetworkIn-Warning
      AlarmDescription: EKS节点网络入口带宽 - Warning级别告警
      Metrics:
      - Id: m1
        ReturnData: true
        Expression:
          Fn::Sub: SELECT MAX(NetworkIn) FROM "AWS/EC2" WHERE "eks:cluster-name" = '${EKSClusterName}' GROUP BY InstanceId ORDER BY MAX() DESC
        Period: 300
      Threshold: 314572800
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  EKSEC2NetworkOutInfoAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName:
        Fn::Sub: ${BusinessTagValue}-EKS-${EKSClusterName}-EC2-NetworkOut-Info
      AlarmDescription: EKS节点网络出口带宽 - Info级别告警
      Metrics:
      - Id: m1
        ReturnData: true
        Expression:
          Fn::Sub: SELECT MAX(NetworkOut) FROM "AWS/EC2" WHERE "eks:cluster-name" = '${EKSClusterName}' GROUP BY InstanceId ORDER BY MAX() DESC
        Period: 300
      Threshold: 157286400
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  EKSEC2NetworkOutWarningAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName:
        Fn::Sub: ${BusinessTagValue}-EKS-${EKSClusterName}-EC2-NetworkOut-Warning
      AlarmDescription: EKS节点网络出口带宽 - Warning级别告警
      Metrics:
      - Id: m1
        ReturnData: true
        Expression:
          Fn::Sub: SELECT MAX(NetworkOut) FROM "AWS/EC2" WHERE "eks:cluster-name" = '${EKSClusterName}' GROUP BY InstanceId ORDER BY MAX() DESC
        Period: 300
      Threshold: 314572800
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  EKSEC2StatusCheckFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName:
        Fn::Sub: ${BusinessTagValue}-EKS-${EKSClusterName}-EC2-StatusCheckFailed-Critical
      AlarmDescription: EKS节点状态检查失败 - 系统或实例问题
      Metrics:
      - Id: m1
        ReturnData: true
        Expression:
          Fn::Sub: SELECT MAX(StatusCheckFailed) FROM "AWS/EC2" WHERE "eks:cluster-name" = '${EKSClusterName}' GROUP BY InstanceId ORDER BY MAX() DESC
        Period: 300
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  EKSEC2StatusCheckFailedSystemAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName:
        Fn::Sub: ${BusinessTagValue}-EKS-${EKSClusterName}-EC2-StatusCheckFailed_System-Critical
      AlarmDescription: EKS节点系统状态检查失败 - AWS基础设施问题
      Metrics:
      - Id: m1
        ReturnData: true
        Expression:
          Fn::Sub: SELECT MAX(StatusCheckFailed_System) FROM "AWS/EC2" WHERE "eks:cluster-name" = '${EKSClusterName}' GROUP BY InstanceId ORDER BY MAX() DESC
        Period: 300
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  EKSEC2StatusCheckFailedInstanceAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName:
        Fn::Sub: ${BusinessTagValue}-EKS-${EKSClusterName}-EC2-StatusCheckFailed_Instance-Critical
      AlarmDescription: EKS节点实例状态检查失败 - 实例配置问题
      Metrics:
      - Id: m1
        ReturnData: true
        Expression:
          Fn::Sub: SELECT MAX(StatusCheckFailed_Instance) FROM "AWS/EC2" WHERE "eks:cluster-name" = '${EKSClusterName}' GROUP BY InstanceId ORDER BY MAX() DESC
        Period: 300
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  EKSEC2StatusCheckFailedAttachedEBSAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName:
        Fn::Sub: ${BusinessTagValue}-EKS-${EKSClusterName}-EC2-StatusCheckFailed_AttachedEBS-Critical
      AlarmDescription: EKS节点附加EBS卷状态检查失败 - 存储连接问题
      Metrics:
      - Id: m1
        ReturnData: true
        Expression:
          Fn::Sub: SELECT MAX(StatusCheckFailed_AttachedEBS) FROM "AWS/EC2" WHERE "eks:cluster-name" = '${EKSClusterName}' GROUP BY InstanceId ORDER BY MAX() DESC
        Period: 60
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 10
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
