AWSTemplateFormatVersion: '2010-09-09'
Description: Tag-Based CloudWatch Alarms for EC2, NAT Gateway, and VPN (10 alarms)

Parameters:
  TagKey:
    Type: String
    Description: Tag key to filter resources (e.g., Environment, Team, Application)
    AllowedPattern: .+
    ConstraintDescription: TagKey is required and cannot be empty

  TagValue:
    Type: String
    Description: Tag value to filter resources (e.g., Production, Staging, UAT)
    AllowedPattern: .+
    ConstraintDescription: TagValue is required and cannot be empty

  SNSTopicArn:
    Type: String
    Description: SNS Topic ARN for alarm notifications (REQUIRED - alarms will not notify without this)
    AllowedPattern: arn:aws:sns:[a-z0-9-]+:[0-9]{12}:.+
    ConstraintDescription: Must be a valid SNS Topic ARN (e.g., arn:aws:sns:ap-southeast-2:123456789012:my-topic)

Resources:
  # =============================================================================
  # EC2 Alarms (7 alarms)
  # =============================================================================

  # EC2 Alarm 1: CPUUtilization
  EC2CPUUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${TagValue}-EC2-CPUUtilization_WARNING"
      AlarmDescription: 服务器CPU使用率超过90%
      Metrics:
        - Id: m1
          ReturnData: true
          Expression: !Sub >-
            SELECT MAX(CPUUtilization) FROM "AWS/EC2"
            WHERE tag.${TagKey} = '${TagValue}'
            GROUP BY tag.Name ORDER BY MAX() DESC
          Period: 300
      Threshold: 90
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref SNSTopicArn

  # EC2 Alarm 2: mem_used_percent (CWAgent)
  EC2MemoryUsedPercentAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${TagValue}-EC2-MemoryUsedPercent_WARNING"
      AlarmDescription: 服务器内存使用率超过90% (需要CloudWatch Agent)
      Metrics:
        - Id: m1
          ReturnData: true
          Expression: !Sub >-
            SELECT MAX(mem_used_percent) FROM "CWAgent"
            WHERE tag.${TagKey} = '${TagValue}'
            GROUP BY tag.Name ORDER BY MAX() DESC
          Period: 300
      Threshold: 90
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref SNSTopicArn

  # EC2 Alarm 3: disk_used_percent (CWAgent)
  EC2DiskUsedPercentAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${TagValue}-EC2-DiskUsedPercent_WARNING"
      AlarmDescription: 服务器磁盘使用率超过90% (需要CloudWatch Agent)
      Metrics:
        - Id: m1
          ReturnData: true
          Expression: !Sub >-
            SELECT MAX(disk_used_percent) FROM "CWAgent"
            WHERE tag.${TagKey} = '${TagValue}'
            GROUP BY tag.Name ORDER BY MAX() DESC
          Period: 300
      Threshold: 90
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref SNSTopicArn

  # EC2 Alarm 4: disk_inodes_used_percent (CWAgent)
  EC2DiskInodesUsedPercentAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${TagValue}-EC2-DiskInodesUsedPercent_WARNING"
      AlarmDescription: 服务器磁盘inode使用率超过90% (需要CloudWatch Agent)
      Metrics:
        - Id: m1
          ReturnData: true
          Expression: !Sub >-
            SELECT MAX(disk_inodes_used_percent) FROM "CWAgent"
            WHERE tag.${TagKey} = '${TagValue}'
            GROUP BY tag.Name ORDER BY MAX() DESC
          Period: 300
      Threshold: 90
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref SNSTopicArn

  # EC2 Alarm 5: StatusCheckFailed_System
  EC2StatusCheckFailedSystemAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${TagValue}-EC2-StatusCheckFailedSystem_WARNING"
      AlarmDescription: EC2系统状态检查失败 - AWS基础设施问题
      Metrics:
        - Id: m1
          ReturnData: true
          Expression: !Sub >-
            SELECT MAX(StatusCheckFailed_System) FROM "AWS/EC2"
            WHERE tag.${TagKey} = '${TagValue}'
            GROUP BY tag.Name ORDER BY MAX() DESC
          Period: 300
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref SNSTopicArn

  # EC2 Alarm 6: StatusCheckFailed
  EC2StatusCheckFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${TagValue}-EC2-StatusCheckFailed_WARNING"
      AlarmDescription: EC2状态检查失败 - 系统或实例问题
      Metrics:
        - Id: m1
          ReturnData: true
          Expression: !Sub >-
            SELECT MAX(StatusCheckFailed) FROM "AWS/EC2"
            WHERE tag.${TagKey} = '${TagValue}'
            GROUP BY tag.Name ORDER BY MAX() DESC
          Period: 300
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref SNSTopicArn

  # EC2 Alarm 7: StatusCheckFailed_Instance
  EC2StatusCheckFailedInstanceAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${TagValue}-EC2-StatusCheckFailedInstance_WARNING"
      AlarmDescription: EC2实例状态检查失败 - 实例配置问题
      Metrics:
        - Id: m1
          ReturnData: true
          Expression: !Sub >-
            SELECT MAX(StatusCheckFailed_Instance) FROM "AWS/EC2"
            WHERE tag.${TagKey} = '${TagValue}'
            GROUP BY tag.Name ORDER BY MAX() DESC
          Period: 300
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref SNSTopicArn

  # =============================================================================
  # NAT Gateway Alarms (1 alarm)
  # =============================================================================

  # NAT Gateway Alarm 1: ErrorPortAllocation
  NATGatewayErrorPortAllocationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${TagValue}-NATGateway-ErrorPortAllocation_WARNING"
      AlarmDescription: NAT网关端口分配错误超过100次
      Metrics:
        - Id: m1
          ReturnData: true
          Expression: !Sub >-
            SELECT MAX(ErrorPortAllocation) FROM "AWS/NATGateway"
            WHERE tag.${TagKey} = '${TagValue}'
            GROUP BY NatGatewayId ORDER BY MAX() DESC
          Period: 300
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref SNSTopicArn

  # =============================================================================
  # VPN Alarms (2 alarms)
  # =============================================================================

  # VPN Alarm 1: TunnelState (connection-level)
  VPNTunnelStateConnectionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${TagValue}-VPN-TunnelState-Connection_WARNING"
      AlarmDescription: VPN连接隧道状态异常 - 连接级别监控
      Metrics:
        - Id: m1
          ReturnData: true
          Expression: !Sub >-
            SELECT MAX(TunnelState) FROM "AWS/VPN"
            WHERE tag.${TagKey} = '${TagValue}'
            GROUP BY VpnId ORDER BY MAX() DESC
          Period: 300
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref SNSTopicArn

  # VPN Alarm 2: TunnelState (tunnel-level)
  VPNTunnelStateTunnelAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${TagValue}-VPN-TunnelState-Tunnel_WARNING"
      AlarmDescription: VPN隧道状态异常 - 隧道级别监控
      Metrics:
        - Id: m1
          ReturnData: true
          Expression: !Sub >-
            SELECT MAX(TunnelState) FROM "AWS/VPN"
            WHERE tag.${TagKey} = '${TagValue}'
            GROUP BY VpnId, TunnelIpAddress ORDER BY MAX() DESC
          Period: 300
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref SNSTopicArn

Outputs:
  AlarmCount:
    Description: Total number of alarms in this template
    Value: "10"

  EC2AlarmCount:
    Description: Number of EC2 alarms
    Value: "7"

  NATGatewayAlarmCount:
    Description: Number of NAT Gateway alarms
    Value: "1"

  ALBAlarmCount:
    Description: Number of ALB alarms (moved to resource-based)
    Value: "0"

  VPNAlarmCount:
    Description: Number of VPN alarms
    Value: "2"

  TagBasedServices:
    Description: Services monitored by this tag-based template
    Value: "EC2, NAT Gateway, VPN"
