AWSTemplateFormatVersion: '2010-09-09'
Description: AWS WAF CloudWatch Alarms
Parameters:
  SNSTopicArn:
    Type: String
    Description: SNS Topic ARN for alarm notifications
    AllowedPattern: arn:aws:sns:[a-z0-9-]+:[0-9]{12}:.+
    ConstraintDescription: Must be a valid SNS Topic ARN
Resources:
  AWSWAFWarningAlarm0:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-AWSWAF-k8s-dify-waf-BlockedRequests-Warning
      AlarmDescription: WAF触发拦截机制 - 检测到异常流量被拦截
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(BlockedRequests) FROM "AWS/WAFV2" WHERE WebACL = 'k8s-dify-waf'
        Period: 300
      Threshold: 50
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  AWSWAFInfoAlarm1:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-AWSWAF-k8s-dify-waf-AllowedRequests-Info
      AlarmDescription: WAF允许的请求数 - 监控正常流量
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(AllowedRequests) FROM "AWS/WAFV2" WHERE WebACL = 'k8s-dify-waf'
        Period: 300
      Threshold: 10000
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
