AWSTemplateFormatVersion: '2010-09-09'
Description: DocumentDB CloudWatch Alarms
Parameters:
  SNSTopicArn:
    Type: String
    Description: SNS Topic ARN for alarm notifications
    AllowedPattern: arn:aws:sns:[a-z0-9-]+:[0-9]{12}:.+
    ConstraintDescription: Must be a valid SNS Topic ARN
Resources:
  DocumentDBInfoAlarm0:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-CPUUtilization-Info
      AlarmDescription: DocumentDB CPU使用率
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(CPUUtilization) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 70
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBWarningAlarm1:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-CPUUtilization-Warning
      AlarmDescription: DocumentDB CPU使用率
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(CPUUtilization) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBCriticalAlarm2:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-CPUUtilization-Critical
      AlarmDescription: DocumentDB CPU使用率
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(CPUUtilization) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 90
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBInfoAlarm3:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-DatabaseConnections-Info
      AlarmDescription: DocumentDB连接数
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(DatabaseConnections) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBWarningAlarm4:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-DatabaseConnections-Warning
      AlarmDescription: DocumentDB连接数
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(DatabaseConnections) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 200
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBCriticalAlarm5:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-DatabaseConnections-Critical
      AlarmDescription: DocumentDB连接数
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(DatabaseConnections) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 300
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBInfoAlarm6:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-FreeableMemory-Info
      AlarmDescription: DocumentDB可用内存 - 低于1GB (1GB in bytes)
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(FreeableMemory) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 1073741824
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBWarningAlarm7:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-FreeableMemory-Warning
      AlarmDescription: DocumentDB可用内存 - 低于512MB (512MB in bytes)
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(FreeableMemory) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 536870912
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBCriticalAlarm8:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-FreeableMemory-Critical
      AlarmDescription: DocumentDB可用内存 - 低于256MB (256MB in bytes)
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(FreeableMemory) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 268435456
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBWarningAlarm9:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-ReadIOPS-Warning
      AlarmDescription: DocumentDB读IOPS
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(ReadIOPS) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 5000
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBCriticalAlarm10:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-ReadIOPS-Critical
      AlarmDescription: DocumentDB读IOPS
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(ReadIOPS) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 10000
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBWarningAlarm11:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-WriteIOPS-Warning
      AlarmDescription: DocumentDB写IOPS
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(WriteIOPS) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 5000
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBCriticalAlarm12:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-WriteIOPS-Critical
      AlarmDescription: DocumentDB写IOPS
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(WriteIOPS) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 10000
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBWarningAlarm13:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-ReadLatency-Warning
      AlarmDescription: DocumentDB读延迟 - 超过10ms
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(ReadLatency) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 0.01
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBCriticalAlarm14:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-ReadLatency-Critical
      AlarmDescription: DocumentDB读延迟 - 超过20ms
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(ReadLatency) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 0.02
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBWarningAlarm15:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-WriteLatency-Warning
      AlarmDescription: DocumentDB写延迟 - 超过10ms
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(WriteLatency) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 0.01
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBCriticalAlarm16:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-WriteLatency-Critical
      AlarmDescription: DocumentDB写延迟 - 超过20ms
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(WriteLatency) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 0.02
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBWarningAlarm17:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-DBInstanceReplicaLag-Warning
      AlarmDescription: DocumentDB复制延迟 - 超过1秒
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(DBInstanceReplicaLag) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 1000
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBCriticalAlarm18:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-DBInstanceReplicaLag-Critical
      AlarmDescription: DocumentDB复制延迟 - 超过5秒
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(DBInstanceReplicaLag) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 5000
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBInfoAlarm19:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-VolumeBytesUsed-Info
      AlarmDescription: DocumentDB存储使用量 - 超过100GB (100GB in bytes)
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(VolumeBytesUsed) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 107374182400
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBWarningAlarm20:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-VolumeBytesUsed-Warning
      AlarmDescription: DocumentDB存储使用量 - 超过150GB (150GB in bytes)
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(VolumeBytesUsed) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 161061273600
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBWarningAlarm21:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-BufferCacheHitRatio-Warning
      AlarmDescription: DocumentDB缓冲区缓存命中率 - 低于95%表示内存不足
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(BufferCacheHitRatio) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 95
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBWarningAlarm22:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-IndexBufferCacheHitRatio-Warning
      AlarmDescription: DocumentDB索引缓冲区缓存命中率 - 低于95%表示内存不足
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(IndexBufferCacheHitRatio) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 95
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBWarningAlarm23:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-DatabaseCursors-Warning
      AlarmDescription: DocumentDB游标数量 - 接近最大值4560
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(DatabaseCursors) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 4000
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBInfoAlarm24:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-DatabaseCursorsTimedOut-Info
      AlarmDescription: DocumentDB游标超时数量 - 应用程序未正确关闭游标
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(DatabaseCursorsTimedOut) FROM "AWS/DocDB" WHERE DBClusterIdentifier
          = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
  DocumentDBCriticalAlarm25:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EM-SNC-CLOUD-DocumentDB-docdb-2026-01-07-11-29-01-DBClusterReplicaLagMaximum-Critical
      AlarmDescription: DocumentDB集群最大复制延迟 - 超过5秒
      Metrics:
      - Id: m1
        ReturnData: true
        Expression: SELECT max(DBClusterReplicaLagMaximum) FROM "AWS/DocDB" WHERE
          DBClusterIdentifier = 'docdb-2026-01-07-11-29-01'
        Period: 300
      Threshold: 5000
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      TreatMissingData: notBreaching
      AlarmActions:
      - Ref: SNSTopicArn
